### ISSUE TITLE
stringToTerm does not validate URIs 

### ISSUE THREAD

**Issue by mielvds** [rubensworks/rdf-string.js#4]
The methods `stringToTerm`allows you to create a `NamedNode`with whatever value, while only IRIs are in fact "possible". See https://github.com/rubensworks/rdf-string.js/blob/master/lib/TermUtil.ts#L100

The fact whether it should do this kind of validation is debatable, because both [N3.js](https://github.com/rdfjs/N3.js) and the [RDFJS spec](http://rdf.js.org/#design-elements-and-principles) don't mention this at object level. 
However, it seem literals that literals are being validated (https://github.com/rubensworks/rdf-string.js/blob/master/lib/TermUtil.ts#L77), so IRIs might as well.

**Comment by rubensworks** [comment]
Perhaps it would be better to do this kind of validation externally (in another function/package).

The problem is that this validation won't be free CPU-wise, so in cases where validation is already done on a higher level, `stringToTerm` would re-validate the URI again, even if it's not necessary anymore.

It would be useful to have a `DataFactory` that wraps over an existing `DataFactory`, and performs these kinds of validations. This way, the validation is still in the hands of the user, and will only be done if it's actually needed.

**Comment by mielvds** [comment]
ok, but CPU time is used to validate literals which could have been validated before too? 
While I'm all for having separate packages, we should maintain oversight. This is a package that deals with strings in the wild (which N3.js clearly doesn't (anymore)), so that's I think it makes somewhat sense. How about a `strict` mode?

**Comment by rubensworks** [comment]
> ok, but CPU time is used to validate literals which could have been validated before too?

The main purpose of the literal regex is merely to get the important parts out of it, validation is just a free bonus here :-)

Also note that the literal validation only applies to the string-version of literals. For RDFJS terms, this is not relevant anymore.

> How about a strict mode?

I don't think this package is the place for that. A `DataFactory` wrapper that does this kind of validation feels cleaner to me.

**Comment by mielvds** [comment]
okay!
